version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python /app/webpage/manage.py wait_for_db &&
             python /app/webpage/manage.py migrate &&
             python /app/webpage/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kaveri@1605

    depends_on:
      - pg
  
  pg:
    image: dpage/pgadmin4
    environment:
      - PGADMINDEFAULTEMAIL = admin@admin.com
      - PGADMINDEFAULTPASSWORD = Kaveri@1605